name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install dependencies for building (CMake and build-essential)
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential

    # Create a build directory inside the mathutils folder and run CMake from it
    - name: Create build directory and run CMake
      run: mkdir -p build && cd build && cmake ../mathutils

    # Build the project with make
    - name: Build project
      run: cd build && make

    # Run tests if available (make check)
    - name: Run tests
      run: cd build && make check

    # Optionally, run distcheck or other checks (if defined in Makefile)
    - name: Run distcheck (if applicable)
      run: cd build && make distcheck
