name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install dependencies for building (CMake and build-essential)
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential

    # Create a build directory and run CMake
    - name: Create build directory
      run: mkdir build && cd build

    - name: Run CMake
      run: cmake ..

    # Build the project with make
    - name: Build project
      run: make

    # Run tests if available (for example, if using make check)
    - name: Run tests
      run: make check

    # Optionally, run distcheck or other clean build checks if needed
    - name: Run distcheck (if applicable)
      run: make distcheck
