name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install dependencies for building and running autoconf (if needed)
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y autoconf automake build-essential

    # Ensure configure script is executable
    - name: Ensure configure script is executable
      run: chmod +x ./configure

    # Run configure (if your project has the configure script)
    - name: configure
      run: ./configure

    # Build the project
    - name: make
      run: make

    # Run tests (check target)
    - name: make check
      run: make check

    # Run distcheck (ensure clean build)
    - name: make distcheck
      run: make distcheck
